---
name: 'lint'

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run hadolint
        uses: brpaz/hadolint-action@1623ba61710b974b55ba455930e6f2c8ef919778
        # v1.3.1 => 1623ba61710b974b55ba455930e6f2c8ef919778

  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run markdown-lint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
        # v1.5.0 => 04d43ee9191307b50935a753da3b775ab695eceb
        with:
          config: '.github/linters/.markdown-lint.yml'
          args: './README.md'

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@d586102c117f97e63d7e3b56629d269efc9a7c60
        # 1.0.0 => d586102c117f97e63d7e3b56629d269efc9a7c60
        env:
          # keep in sync with tests/shellcheck-exclude
          SHELLCHECK_OPTS: -e SC1001 -e SC1003 -e SC1090 -e SC1091 -e SC1117 -e SC2029 -e SC2034 -e SC2046 -e SC2064 -e SC2068 -e SC2086 -e SC2119 -e SC2120 -e SC2128 -e SC2148 -e SC2153 -e SC2154 -e SC2155 -e SC2162 -e SC2174 -e SC2179 -e SC2191 -e SC2199 -e SC2207 -e SC2219 -e SC2220 -e SC2230 -e SC2231 -e SC2235

  shfmt:
    name: shfmt
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run shfmt
        uses: luizm/action-sh-checker@442951059cb22d260c6e69309ae59cb7bb2334b8
        # v0.1.12 => 442951059cb22d260c6e69309ae59cb7bb2334b8
        env:
          SHFMT_OPTS: -l -bn -ci -i 2 -d
        with:
          sh_checker_shellcheck_disable: true

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@b2aeacc1b7eeb8c23e84bba320d04fb5d6a323ee
        # v3.0.0 => b2aeacc1b7eeb8c23e84bba320d04fb5d6a323ee
        with:
          config_file: '.github/linters/.yamllint.yml'
